name: Run tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# Cancel job when new commit is pushed for the same build
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
# https://github.com/OSGeo/gdal/pull/5460
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['17']

    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
